### ISSUE TITLE
question regarding -t

### ISSUE THREAD

**Issue by kaoscoach** [job/aggregate6#19]
Great tool. Very helpful. Can you explain what the -t option does? I have tried using it multiple times with and without it and it returns the same output. Just confused on what you mean by "truncate IP/mask to network/mask"?

thanks,

**Comment by job** [comment]
See this example without and with `-t`:

```
$ echo 10.1.2.3/24 | aggregate6    
ERROR: '10.1.2.3/24' is not a valid IP network, ignoring.

$ echo 10.1.2.3/24 | aggregate6 -t 
10.1.2.0/24
```

the `-t` option converts host addresses into network addresses
